version: '3.7'
services: 
    crawlers:
        image: python:3.10.4-alpine
        container_name: crawlers
        working_dir: /python-crawlers
        stdin_open: true
        tty: true
        volumes:
          - .:/python-crawlers
        networks:
          - crawlers
networks:
    crawlers:
        external: true